### ISSUE TITLE
Internal error triggered by ProphesizeDynamicReturnTypeExtension::getTypeFromMethodCall with phpspec/prophecy 1.18

### ISSUE THREAD

**Issue by InvisibleSmiley** [Jan0707/phpstan-prophecy#315] opened 2023-12-11 12:59 UTC
#### Steps required to reproduce the problem

1. Start with a project using phpstan/phpstan 1.10.48, phpstan/phpstan-phpunit 1.13.15, phpspec/prophecy dev-master, phpspec-prophecy-phpunit dev-master, and some tests using Prophecy like `(new Prophet())->prophesize(Some::class)`
2. Upgrade phpspec/prophecy to 1.18 (from dev-master)

#### Expected Result

* PHPStan finished without internal errors

#### Actual Result

* PHPStan runs into an internal error

Xdebug analysis shows that the difference before/after is in `ProphesizeDynamicReturnTypeExtension::getTypeFromMethodCall` line 70 where the `$returnType` instanceof check used to be true but is not anymore:
- before: GenericObjectType
- after: ConditionalTypeForParameter

**Comment by danepowell** [comment] 2023-12-11 19:07
Definitely a regression in 1.18. Here's a full stacktrace: https://github.com/phpstan/phpstan/issues/10272#issuecomment-1847569372

**Comment by danepowell** [comment] 2023-12-15 21:54
Since this appears to be a breaking change in phpspec/prophecy, is it worth opening an issue there?

**Comment by nikophil** [comment] 2024-01-02 10:03
Hello @danepowell 

is there an issue opened in `phpspec/prophecy`? I can't find it

**Comment by danepowell** [comment] 2024-01-02 21:31
I've not had time to open an issue with phpspec/prophecy

**Comment by JustusNBB** [comment] 2024-02-15 11:32
I think I've also hit this: https://github.com/phpstan/phpstan/issues/10582
Would you please confirm it's the same issue? Any chance of getting #316 merged soon?

**Comment by danepowell** [comment] 2024-02-15 23:43
> Since this appears to be a breaking change in phpspec/prophecy, is it worth opening an issue there?

To be clear, I proposed opening an issue in phpspec/prophecy only to document (and to some degree, complain about :smile: ) the undocumented breaking change. But ultimately, I think this needs to be fixed via #316

**Closed** 2024-03-04 08:01 UTC
